# Default page title
title: Uberfire Framework

# Project id name
project: uberfire

# Project full name
project_name: Uberfire

# Default minify settings
css_minifier: disabled
js_minifier: disabled
html_minifier: disabled

# Merge multiple JavaScript files to improve performance
fileMerger:
  enabled: true
  outputFilePath: /javascripts/bootstrap-community.js
  paths:
    - /javascripts/_bootstrap-transition.js
    - /javascripts/_bootstrap-alert.js
    - /javascripts/_bootstrap-button.js
    - /javascripts/_bootstrap-carousel.js
    - /javascripts/_bootstrap-collapse.js
    - /javascripts/_bootstrap-dropdown.js
    - /javascripts/_bootstrap-modal.js
    - /javascripts/_bootstrap-tooltip.js
    - /javascripts/_bootstrap-popover.js
    - /javascripts/_bootstrap-scrollspy.js
    - /javascripts/_bootstrap-tab.js
    - /javascripts/_bootstrap-affix.js
    - /javascripts/_jbossorg-navbarfix.js
    - /javascripts/_jbossorg-FeedEk.js
    - /javascripts/_jbossorg-jiraWidget.js
    - /javascripts/_jquery-easytabs.js
    - /javascripts/_crisp-scripts.js
    - /javascripts/_jbossorg-tabzilla.js

# Cache hosted fonts, images and javascript
wget:
  enabled: true
  rerunEach: 86400 # seconds
  timestampFilename: _wget-timestamp
  options:
    - --no-remove-listing
    - -q
    - -r
    - --no-parent
    - -N
    - --reject 'index.html*'
    - -e robots=off
    - --directory-prefix=cache
  urls:
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.js
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.min.js
    - http://static.jboss.org/theme/js/libs/html5/pre3.6/html5.min.js
    - http://static.jboss.org/theme/js/libs/prettify/188.0.0/prettify.min.js
    - http://static.jboss.org/theme/js/libs/holder/1.9/holder.js
    - http://static.jboss.org/theme/fonts/titilliumtext/
    - http://static.jboss.org/uberfire/fonts/sourcesanspro/
    - http://static.jboss.org/theme/fonts/font-awesome/
    - http://static.jboss.org/theme/images/common/
    - http://static.jboss.org/uberfire/

# Update resource URLs based on the profile
profiles:
  development:
    jborg_fonts_url: /cache/static.jboss.org/uberfire/fonts
    jborg_images_url: /cache/static.jboss.org/theme/images
    jborg_js_url: /cache/static.jboss.org/theme/js
    project_images_url: /upload/images
    project_fonts_url: /upload/fonts
    bootstrap_css_url: /stylesheets-source/_bootstrap-community
    bootstrap_js_url: /javascripts/bootstrap-community
    base_url: http://uberfireframework.org/
    symlinker:
      from: ../stylesheets
      to: ./_site/stylesheets-source
